import { createStitches } from '@stitches/react';

export const {
  styled,
  css,
  globalCss,
  keyframes,
  theme,
  createTheme,
  config,
  getCssText,
} = createStitches({
  theme: {
    colors: {
      primary: '#e23744',
      primaryDeep: '#c62828',
      primarySoft: '#ff6f61',
      onPrimary: '#ffffff',
      inkButton: '#1c1c1c',
      onInkButton: '#ffffff',
      success: '#2e7d32',
      successBg: '#e8f5e9',
      attention: '#f2a918',
      warning: '#f9a825',
      warningBg: '#fff8e1',
      critical: '#e41e3f',
      criticalStrong: '#c62828',
      info: '#1565c0',
      infoBg: '#e3f2fd',
      canvas: '#ffffff',
      surfaceSoft: '#f8f9fa',
      surfaceWarm: '#fff5f5',
      inkDeep: '#1c1c1c',
      ink: '#333333',
      charcoal: '#555555',
      slate: '#666666',
      steel: '#888888',
      stone: '#aaaaaa',
      hairline: '#dddddd',
      hairlineSoft: '#eeeeee',
      disabledText: '#cccccc',
      // Admin backward-compatible aliases
      secondary: '#2e3a59',
      background: '#ffffff',
      surface: '#f1f4f7',
      text: '#2f3542',
      textMuted: '#747d8c',
      border: '#e4e7eb',
      danger: '#e41e3f',
      primaryHover: '#ff6b81',
    },
    space: {
      1: '4px',
      2: '8px',
      3: '10px',
      4: '12px',
      5: '16px',
      6: '20px',
      7: '24px',
      8: '32px',
      9: '40px',
      10: '48px',
      11: '64px',
      12: '80px',
      13: '120px',
    },
    fontSizes: {
      1: '12px',
      2: '14px',
      3: '16px',
      4: '18px',
      5: '24px',
      6: '28px',
      7: '36px',
      8: '48px',
      9: '64px',
    },
    fonts: {
      system: 'Inter, -apple-system, BlinkMacSystemFont, "Helvetica Neue", Helvetica, Arial, sans-serif',
    },
    fontWeights: {
      light: '300',
      regular: '400',
      medium: '500',
      semibold: '600',
      bold: '700',
    },
    lineHeights: {
      none: '1',
      tight: '1.16',
      snug: '1.25',
      normal: '1.5',
      relaxed: '1.43',
    },
    letterSpacings: {
      tight: '-0.16px',
      snug: '-0.14px',
      normal: '0',
    },
    sizes: {
      maxContainer: '1280px',
    },
    borderWidths: {
      1: '1px',
      2: '2px',
    },
    borderStyles: {},
    radii: {
      xs: '2px',
      sm: '4px',
      md: '6px',
      lg: '8px',
      xl: '16px',
      xxl: '24px',
      xxxl: '32px',
      feature: '40px',
      full: '100px',
      circle: '9999px',
    },
    shadows: {
      none: 'none',
      subtle: 'rgba(0, 0, 0, 0.2) 1px 1px 0px 0px',
      sticky: 'rgba(20, 22, 26, 0.3) 0px 1px 4px 0px',
      sm: '0 2px 4px rgba(0, 0, 0, 0.04)',
      md: '0 4px 12px rgba(0, 0, 0, 0.06)',
      lg: '0 10px 25px rgba(0, 0, 0, 0.1)',
      glass: '0 8px 32px 0 rgba(31, 38, 135, 0.07)',
    },
    zIndices: {
      under: '-1',
      base: '1',
      nav: '100',
      modal: '1000',
    },
    transitions: {
      all: 'all 0.2s ease',
    },
  },
  media: {
    mobile: '(max-width: 479px)',
    mobileLg: '(max-width: 767px)',
    tablet: '(max-width: 1023px)',
    desktop: '(min-width: 1024px)',
    wide: '(min-width: 1360px)',
  },
  utils: {
    m: (value: string | number) => ({ margin: value }),
    mt: (value: string | number) => ({ marginTop: value }),
    mr: (value: string | number) => ({ marginRight: value }),
    mb: (value: string | number) => ({ marginBottom: value }),
    ml: (value: string | number) => ({ marginLeft: value }),
    mx: (value: string | number) => ({ marginLeft: value, marginRight: value }),
    my: (value: string | number) => ({ marginTop: value, marginBottom: value }),
    p: (value: string | number) => ({ padding: value }),
    pt: (value: string | number) => ({ paddingTop: value }),
    pr: (value: string | number) => ({ paddingRight: value }),
    pb: (value: string | number) => ({ paddingBottom: value }),
    pl: (value: string | number) => ({ paddingLeft: value }),
    px: (value: string | number) => ({ paddingLeft: value, paddingRight: value }),
    py: (value: string | number) => ({ paddingTop: value, paddingBottom: value }),
    size: (value: string | number) => ({ width: value, height: value }),
  },
});

export const darkTheme = createTheme('dark-theme', {
  colors: {
    primary: '#ff4757',
    primaryHover: '#ff6b81',
    secondary: '#a4b0be',
    background: '#1e272e',
    surface: '#2f3542',
    text: '#f1f2f6',
    textMuted: '#a4b0be',
    border: '#3f4656',
    glassBg: 'rgba(47, 53, 66, 0.75)',
    glassBorder: 'rgba(255, 255, 255, 0.08)',
    shadowColor: 'rgba(0, 0, 0, 0.3)',
  },
  shadows: {
    sm: '0 2px 4px rgba(0, 0, 0, 0.2)',
    md: '0 4px 12px rgba(0, 0, 0, 0.3)',
    lg: '0 10px 25px rgba(0, 0, 0, 0.4)',
    glass: '0 8px 32px 0 rgba(0, 0, 0, 0.3)',
  },
});

export const fadeIn = keyframes({
  '0%': { opacity: 0, transform: 'translateY(10px)' },
  '100%': { opacity: 1, transform: 'translateY(0)' },
});

export const heartbeat = keyframes({
  '0%': { transform: 'scale(1)' },
  '14%': { transform: 'scale(1.04)' },
  '28%': { transform: 'scale(1)' },
  '42%': { transform: 'scale(1.04)' },
  '70%': { transform: 'scale(1)' },
});
