#!/bin/bash
# ═══════════════════════════════════════════════════════
# Free Deployment Script — The Katanguri's Kitchen
# Deploys to Vercel (web + admin) and Render (API)
# ═══════════════════════════════════════════════════════

set -e

echo "🍳 The Katanguri's Kitchen — Free Deployment"
echo "═══════════════════════════════════════════════"
echo ""

# Check prerequisites
command -v node >/dev/null 2>&1 || { echo "❌ Node.js not found. Install from https://nodejs.org"; exit 1; }
command -v npm >/dev/null 2>&1 || { echo "❌ npm not found."; exit 1; }

# Check if Vercel CLI is installed
if ! command -v vercel &> /dev/null; then
    echo "📦 Installing Vercel CLI..."
    npm install -g vercel
fi

echo ""
echo "═══════════════════════════════════════════════"
echo "  STEP 1: Deploy Web App to Vercel"
echo "═══════════════════════════════════════════════"
echo ""
echo "📋 Before deploying, you need:"
echo "   1. A Vercel account (sign up at vercel.com)"
echo "   2. A Supabase project (free at supabase.com)"
echo "   3. An Upstash Redis database (free at upstash.com)"
echo ""
read -p "Press Enter when ready to deploy web app..."
cd apps/web
vercel --prod
cd ../..

echo ""
echo "═══════════════════════════════════════════════"
echo "  STEP 2: Deploy Admin Dashboard to Vercel"
echo "═══════════════════════════════════════════════"
echo ""
read -p "Press Enter when ready to deploy admin dashboard..."
cd apps/admin
vercel --prod
cd ../..

echo ""
echo "═══════════════════════════════════════════════"
echo "  STEP 3: Deploy API to Render"
echo "═══════════════════════════════════════════════"
echo ""
echo "📋 Manual steps for Render:"
echo "   1. Go to https://render.com and create an account"
echo "   2. Click 'New +' → 'Blueprint'"
echo "   3. Connect your GitHub repo"
echo "   4. Render will detect render.yaml automatically"
echo "   5. Set environment variables in Render dashboard"
echo "   6. Click 'Deploy'"
echo ""
echo "   Required environment variables:"
echo "   ─────────────────────────────"
echo "   DATABASE_URL=postgresql://..."
echo "   REDIS_URL=rediss://..."
echo "   JWT_SECRET=<auto-generated>"
echo "   JWT_REFRESH_SECRET=<auto-generated>"
echo "   CORS_ORIGINS=https://your-web.vercel.app"
echo "   APP_URL=https://your-web.vercel.app"
echo ""

echo ""
echo "═══════════════════════════════════════════════"
echo "  STEP 4: Set Up Database"
echo "═══════════════════════════════════════════════"
echo ""
echo "📋 After API is deployed:"
echo "   1. Get your Supabase DATABASE_URL"
echo "   2. Run: DATABASE_URL='your-url' npm run db:push"
echo "   3. Run: DATABASE_URL='your-url' npm run seed"
echo ""

echo ""
echo "✅ Deployment script complete!"
echo ""
echo "📖 Full guide: docs/FREE-DEPLOYMENT-GUIDE.md"
echo ""
echo "Monthly cost: \$0"
echo ""
